// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditpageController from "./editpage_controller"
application.register("editpage", EditpageController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ScheduledController from "./scheduled_controller"
application.register("scheduled", ScheduledController)

import ReadMore from 'stimulus-read-more'
application.register('read-more', ReadMore)

// import Carousel from 'stimulus-carousel'
// application.register('carousel', Carousel)
